### Create Book
POST https://api.example.com/books
Content-Type: application/json

{
  "name": "Demo"
}

### Expected 201
HTTP/1.1 201 Created
Content-Type: application/json

{
  "id": "6a0e4d1d-65f6-43e2-8f70-3748fdc75c06",
  "name": "Demo",
  "created_at": "2026-02-08T12:00:00Z"
}

### List Books
GET https://api.example.com/books

### Expected 200
HTTP/1.1 200 OK
Content-Type: application/json

[
  {
    "id": "6a0e4d1d-65f6-43e2-8f70-3748fdc75c06",
    "name": "Demo",
    "created_at": "2026-02-08T12:00:00Z"
  }
]
